### ISSUE TITLE
Empty JSON object reports warnings - ""appears"" to be file name related.

### ISSUE THREAD

**Issue by jeffschwartz** [neoclide/coc-json#14] opened 2019-10-25 21:34 UTC
I have an empty JSON object and there are 2 warning messages:
![Screen Shot 2019-10-25 at 5 28 00 PM](https://user-images.githubusercontent.com/271288/67605616-dc78f300-f74c-11e9-8441-646c6e4715ed.png)

The same file when opened in VSCode reports no warnings:
![Screen Shot 2019-10-25 at 5 29 51 PM](https://user-images.githubusercontent.com/271288/67605748-3d083000-f74d-11e9-9a6b-8cb4a517f820.png)

Another JSON file also with an empty JSON object reports no warnings:
![Screen Shot 2019-10-25 at 5 33 00 PM](https://user-images.githubusercontent.com/271288/67605833-85275280-f74d-11e9-9b70-c64ec74a015a.png)

However, when I change the name of the offending file to triox.json no warnings are reported:
![Screen Shot 2019-10-25 at 5 39 04 PM](https://user-images.githubusercontent.com/271288/67606102-5bbaf680-f74e-11e9-81ba-b3f68d0d2777.png)

**Comment by chemzqm** [comment] 2019-10-26 05:29
Can't reproduce, maybe your coc-json is too old, check `:CocList extensions`

**Comment by jeffschwartz** [comment] 2019-10-26 11:10
Thank you @chemzqm. I have checked as you requested. My version of the coc-json is v1.2.4 and is enabled

![Screen Shot 2019-10-26 at 7 03 36 AM](https://user-images.githubusercontent.com/271288/67618537-c441bc00-f7be-11e9-8812-86e7588001fa.png)

and still getting warning messages
![Screen Shot 2019-10-26 at 7 08 43 AM](https://user-images.githubusercontent.com/271288/67618612-a0cb4100-f7bf-11e9-888a-01c9344dbdce.png)

**Comment by jeffschwartz** [comment] 2019-10-27 18:16
I can't swear to it but I'm thinking that the file name `trrio.manifest.json` is causing the issue, specifically the `manifest.json` part of the name.

I googled `manifest.json` and came it back with this:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json
and the schema there includes both properties that the warning messages are flagging as missing.

![Screen Shot 2019-10-27 at 2 14 12 PM](https://user-images.githubusercontent.com/271288/67639263-22a49280-f8c4-11e9-87a1-990afcda02c7.png)

Let me know if there is anything else I can do to assist in fixing this issue.

**Comment by chemzqm** [comment] 2020-02-06 06:17
Should be fixed now.

**Closed by chemzqm** 2020-02-06 06:17 UTC
Labels: question

**Comment by jeffschwartz** [comment] 2020-02-06 18:10
Yes, it appears to be fixed. Thank you.

**Comment by jeffschwartz** [comment] 2020-02-15 19:11
It's back :)

![Screen Shot 2020-02-15 at 2 02 10 PM](https://user-images.githubusercontent.com/271288/74593700-fee49400-4ffb-11ea-8cd0-7d814b937e84.png)
